### ISSUE TITLE
add Rarbg.to

### ISSUE THREAD

**Issue by renzzla** [autodl-community/autodl-trackers#168]
http://pastebin.com/sR1QvM4N

Not sure how "official" this. is. It seems to be a bot reading the RSS feed from rarbg (public tracker) and announcing on Opentrackers IRC. Would be very useful to have this...thanks.

**Comment by thebigmunch** [comment]
Since you're not sure it's official, that means you haven't spoken to someone at RARBG to check if it's fine with them. This is [something I require](https://github.com/autodl-community/autodl-irssi/wiki/FAQ#how-do-i-get-a-new-tracker-added-to-autodl-irssi) no matter if the tracker is private or public.
